"""CloudGuard — Email alert sender (async SMTP)."""

import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

import aiosmtplib
from config import get_settings

logger = logging.getLogger(__name__)
settings = get_settings()


async def send_email_alert(
    subject: str,
    body_html: str,
    recipient: str | None = None,
) -> bool:
    """Send an HTML email alert. Returns True on success."""
    if not settings.SMTP_HOST:
        logger.warning("SMTP not configured — skipping email alert.")
        return False

    to_addr = recipient or settings.ALERT_EMAIL_TO
    if not to_addr:
        logger.warning("No recipient email configured.")
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"[CloudGuard] {subject}"
    msg["From"] = settings.ALERT_EMAIL_FROM
    msg["To"] = to_addr
    msg.attach(MIMEText(body_html, "html"))

    try:
        await aiosmtplib.send(
            msg,
            hostname=settings.SMTP_HOST,
            port=settings.SMTP_PORT,
            username=settings.SMTP_USER or None,
            password=settings.SMTP_PASSWORD or None,
            start_tls=True,
        )
        logger.info(f"Email alert sent to {to_addr}")
        return True
    except Exception as exc:
        logger.error(f"Failed to send email alert: {exc}")
        return False


def build_scan_report_html(
    scan_id: str,
    risk_score: float,
    counts: dict[str, int],
    total: int,
) -> str:
    """Build a simple HTML summary of a finished scan."""
    return f"""
    <html>
    <body style="font-family: Arial, sans-serif; background: #0f172a; color: #e2e8f0; padding: 24px;">
      <div style="max-width: 600px; margin: auto; background: #1e293b; border-radius: 12px; padding: 32px;">
        <h1 style="color: #38bdf8; margin-top:0;">☁️ CloudGuard Scan Report</h1>
        <p><strong>Scan ID:</strong> {scan_id}</p>
        <p><strong>Risk Score:</strong>
          <span style="font-size: 28px; font-weight: bold; color: {'#ef4444' if risk_score >= 70 else '#f59e0b' if risk_score >= 40 else '#22c55e'};">
            {risk_score}
          </span> / 100
        </p>
        <hr style="border-color: #334155;">
        <h3>Findings Summary ({total} total)</h3>
        <table style="width:100%; border-collapse: collapse;">
          <tr><td style="padding:6px;">🔴 Critical</td><td style="text-align:right;">{counts.get('CRITICAL', 0)}</td></tr>
          <tr><td style="padding:6px;">🟠 High</td><td style="text-align:right;">{counts.get('HIGH', 0)}</td></tr>
          <tr><td style="padding:6px;">🟡 Medium</td><td style="text-align:right;">{counts.get('MEDIUM', 0)}</td></tr>
          <tr><td style="padding:6px;">🟢 Low</td><td style="text-align:right;">{counts.get('LOW', 0)}</td></tr>
        </table>
        <hr style="border-color: #334155;">
        <p style="font-size: 12px; color: #94a3b8;">Generated by CloudGuard CSPM</p>
      </div>
    </body>
    </html>
    """
